apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: database-persistent-volume-persistent-volume-calim 
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi